[versions]
activityCompose = "1.12.2"
anhance = "2025.12.00"
appcompat = "1.7.1"
composeBom = "2025.12.01"
constraintlayout = "1.1.1"
coilCompose = "3.3.0"
coreKtx = "1.17.0"
splashscreen = "1.2.0"
espressoCore = "3.7.0"
firebaseBom = "34.7.0"
hiltNavigation = "1.3.0"
navigation3 = "1.0.0"
junit = "4.13.2"
junitVersion = "1.3.0"
serialization = "1.9.0"
material = "1.13.0"
modify = "0.8.2"

# plugin
kotlin = "2.3.0"
agp = "8.13.2"
ksp = "2.3.3"
hilt = "2.57.2"


[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-graphic = { module = "androidx.compose.ui:ui-graphics" }
androidx-compose-ui-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintlayout" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "splashscreen" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigation" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }

google-firebase-auth = { module = "com.google.firebase:firebase-auth" }
google-firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
google-firebase-firestore = { module = "com.google.firebase:firebase-firestore" }

google-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
google-hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }

androidx-navigation3-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "navigation3" }
androidx-navigation3-ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "navigation3" }

google-material = { module = "com.google.android.material:material", version.ref = "material" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlin-metadata-jvm = { module = "org.jetbrains.kotlin:kotlin-metadata-jvm", version.ref = "kotlin" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
naulian-anhance = { module = "com.naulian:anhance", version.ref = "anhance" }
naulian-modify = { module = "com.naulian:modify", version.ref = "modify" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coilCompose" }
coil-network-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coilCompose" }


[plugins]
application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
google-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
google-hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }





